import type { InspectionCategory } from "../types/inspectionData";

// 検査マスタデータ（現地調査チェックシートより）
export const inspectionMaster: InspectionCategory[] = [
  {
    id: "cat1",
    name: "外部① 敷地及び地盤",
    shortName: "敷地・地盤",
    color: "from-teal-500 to-teal-600",
    emoji: "🏠",
    items: [
      {
        id: "item1",
        num: 1,
        name: "地盤",
        desc: "・建物に接する地盤の1m内外の地盤沈下、土間と基礎立上り接合部の著しい隙間の程度 \n・外構、エントランスアプローチの土間の著しいひび割れ、外構タイル破損",
        evalType: "standard",
      },
      {
        id: "item2",
        num: 2,
        name: "敷地",
        desc: "敷地内の排水桝等の破損、建物の使用や安全上の支障をきたすフェンス、塀、ブロック、外灯、外付倉庫、その他工作物の破損、傾斜、倒壊、規則違反の有無",
        evalType: "standard",
      },
      {
        id: "item3",
        num: 3,
        name: "擁壁（敷地内の地盤面と高低差がある壁）",
        desc: "擁壁の劣化及び損傷、ひび割れ、傾斜の有無",
        evalType: "standard",
        groupId: "group_youheki",
        groupLabel: "擁壁",
      },
      {
        id: "item4",
        num: 4,
        name: "水抜きパイプ",
        desc: "擁壁の水抜きパイプの維持保全の有無",
        evalType: "standard",
        groupId: "group_youheki",
      },
      {
        id: "item5",
        num: 5,
        name: "駐車場",
        desc: "駐車場内の土間ひび割れ、陥没の恐れ",
        evalType: "standard",
        groupId: "group_parking",
        groupLabel: "駐車場",
      },
      {
        id: "item6",
        num: 6,
        name: "駐輪場",
        desc: "駐輪場内の土間ひび割れ、陥没の恐れ",
        evalType: "standard",
        groupId: "group_bicycle",
        groupLabel: "駐輪場",
      },
      {
        id: "item7",
        num: 7,
        name: "建物の周囲（敷地外）",
        desc: "隣接擁壁や、建物及びフェンス等の傾斜、倒壊、接触の恐れ、明らかな越境の有無",
        evalType: "standard",
      },
    ],
  },
  {
    id: "cat2",
    name: "外部② 各点検口内",
    shortName: "点検口内",
    color: "from-blue-500 to-blue-600",
    emoji: "🔍",
    items: [
      // 床下点検口グループ (8-21)
      {
        id: "item8",
        num: 8,
        name: "基礎立ち上り及び底盤",
        desc: "基礎立ち上り及び底盤の著しいひび割れ、劣化又は欠損等の有無（幅0.5mm、深さ20mm程度）",
        evalType: "standard",
        sub: "木造・鉄骨・RC",
        groupId: "group_yukashita",
        groupLabel: "床下点検口",
      },
      {
        id: "item9",
        num: 9,
        name: "広範囲のひび割れ",
        desc: "広範囲にまたぐひび割れの有無",
        evalType: "standard",
        sub: "点検口が使用できない場合、スコープによる調査を実施",
        groupId: "group_yukashita",
      },
      {
        id: "item10",
        num: 10,
        name: "コンクリート劣化",
        desc: "コンクリートの著しい劣化の有無（ジャンカ、豆板又は幅0.5mm未満のひび割れ、深さ20mm未満の欠損が広範囲に発生していない事）",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      {
        id: "item11",
        num: 11,
        name: "さび汁・白華",
        desc: "さび汁、エフロレッセンス(白華現象)、ジャンカの有無",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      {
        id: "item12",
        num: 12,
        name: "鉄筋露出",
        desc: "鉄筋の露出の有無",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      {
        id: "item13",
        num: 13,
        name: "設備配管貫通部",
        desc: "設備配管の基礎貫通部の隙間の有無",
        evalType: "standard",
        sub: "スコープ調査",
        groupId: "group_yukashita",
      },
      {
        id: "item14",
        num: 14,
        name: "基礎底盤水染み",
        desc: "基礎底盤に水たまり又は水染み跡の有無（土の場合は水跡がないこと　土が著しい湿気を含んでいない事）",
        evalType: "standard",
        options: [
          {
            label: "基礎形式",
            choices: ["ベタ基礎", "布基礎", "独立基礎", "杭基礎", "その他"],
          },
        ],
        groupId: "group_yukashita",
      },
      {
        id: "item15",
        num: 15,
        name: "土台・床組",
        desc: "土台及び床組に著しいひび割れ、劣化又は欠損の有無",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      {
        id: "item16",
        num: 16,
        name: "木部腐朽",
        desc: "木部の腐朽、カビの付着の有無（表面上のカビはb2評価）",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      {
        id: "item17",
        num: 17,
        name: "基礎天端隙間",
        desc: "基礎天端（基礎パッキンがある場合は基礎パッキン）と土台の間に著しい隙間、または非構造材が挟まれていない事の有無",
        evalType: "standard",
        options: [
          { label: "換気方法", choices: ["換気口", "基礎パッキン", "無"] },
        ],
        groupId: "group_yukashita",
      },
      {
        id: "item18",
        num: 18,
        name: "床組染み跡",
        desc: "床組に染み跡の有無",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      {
        id: "item19",
        num: 19,
        name: "水漏れ・変形",
        desc: "水漏れ、変形、等の有無",
        evalType: "standard",
        options: [
          {
            label: "断熱工法",
            choices: ["床断熱工法", "基礎断熱工法", "無", "不明"],
          },
        ],
        groupId: "group_yukashita",
      },
      {
        id: "item20",
        num: 20,
        name: "蟻害",
        desc: "蟻害（木造・鉄骨のみ）の有無",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      {
        id: "item21",
        num: 21,
        name: "配管配線接続部",
        desc: "配管及び配線接続部の劣化、脱落の有無",
        evalType: "standard",
        groupId: "group_yukashita",
      },
      // 小屋裏・天井点検口グループ (22-29)
      {
        id: "item22",
        num: 22,
        name: "天井下地材",
        desc: "天井の下地材（せっこうボード等）のひび割れ、欠損、浮き、はらみの有無",
        evalType: "standard",
        sub: "木造・鉄骨・RC",
        groupId: "group_koyaura",
        groupLabel: "小屋裏・天井点検口",
      },
      {
        id: "item23",
        num: 23,
        name: "小屋組劣化",
        desc: "小屋組に著しいひび割れ、劣化又は欠損の有無（鉄骨造の場合、溶接部分の劣化・防錆塗装の劣化（はがれ）等を含む）",
        evalType: "standard",
        groupId: "group_koyaura",
      },
      {
        id: "item24",
        num: 24,
        name: "横架材欠込み",
        desc: "横架材の引っ張り側に欠込みの有無。また、貫通口があった場合、口径は梁成の１/４以下かつ梁成の上下１/3の箇所は避けている事の有無 \n※木質構造設計基準(日本建築学会)",
        evalType: "standard",
        groupId: "group_koyaura",
      },
      {
        id: "item25",
        num: 25,
        name: "雨漏り跡・腐朽",
        desc: "小屋組に雨漏りの跡、腐朽の有無",
        evalType: "standard",
        groupId: "group_koyaura",
      },
      {
        id: "item26",
        num: 26,
        name: "さび汁・白華",
        desc: "さび汁、エフロレッセンス(白華現象)、ジャンカの有無",
        evalType: "standard",
        groupId: "group_koyaura",
      },
      {
        id: "item27",
        num: 27,
        name: "ダクト・配管・配線接続状況",
        desc: "ダクトの接続状況、配管及び配線の接続状況（湿気が小屋裏・天井内に滞留していないか）",
        evalType: "standard",
        options: [
          {
            label: "小屋裏・軒裏換気口の設置",
            choices: ["設置有", "設置無", "不明"],
          },
        ],
        groupId: "group_koyaura",
      },
      {
        id: "item28",
        num: 28,
        name: "耐火被覆",
        desc: "耐火被覆にひび割れ、欠損、剥離などの有無（鉄骨造のみ）",
        evalType: "standard",
        sub: "鉄骨用",
        groupId: "group_koyaura",
      },
      {
        id: "item29",
        num: 29,
        name: "鉄骨部サビ",
        desc: "鉄骨部のサビの有無（防錆措置が講じられているか）（鉄骨造のみ）",
        evalType: "standard",
        groupId: "group_koyaura",
      },
    ],
  },
  {
    id: "cat3",
    name: "外部③ 建築物外部",
    shortName: "建築物外部",
    color: "from-indigo-500 to-indigo-600",
    emoji: "🏢",
    items: [
      // 基礎グループ (30-39)
      {
        id: "item30",
        num: 30,
        name: "コンクリート直仕上げひび割れ",
        desc: "幅0.5㎜以上のひび割れ、0.5mm未満であっても、広範囲に及ぶひび割れの有無",
        evalType: "standard",
        groupId: "group_kiso",
        groupLabel: "基礎",
        finishMaterialKey: "コンクリート直仕上げ",
      },
      {
        id: "item31",
        num: 31,
        name: "コンクリート直仕上げ欠損",
        desc: "深さ20㎜以上の欠損又は、深さが20mm未満であっても広範囲に及ぶ欠損の有無",
        evalType: "standard",
        groupId: "group_kiso",
        finishMaterialKey: "コンクリート直仕上げ",
      },
      {
        id: "item32",
        num: 32,
        name: "モルタル・その他塗り仕上げひび割れ",
        desc: "仕上部分を貫通して基礎コンクリート躯体にまで到達するひび割れ、欠損の有無",
        evalType: "standard",
        sub: "モルタル・その他塗り仕上げ",
        groupId: "group_kiso",
        finishMaterialKey: "モルタル仕上げ・その他塗り仕上げ",
      },
      {
        id: "item33",
        num: 33,
        name: "モルタル・その他塗り仕上げ欠損",
        desc: "仕上部分から下地の基礎コンクリート躯体まで連続し、コンクリート部分における深さが\n20mm以上の欠損又は深さが20mm未満であっても広範囲に及ぶ欠損の有無",
        evalType: "standard",
        groupId: "group_kiso",
        finishMaterialKey: "モルタル仕上げ・その他塗り仕上げ",
      },
      {
        id: "item34",
        num: 34,
        name: "モルタル・その他塗り仕上げ露出",
        desc: "仕上部分が広範囲にわたり下地材から剥離した等の、基礎コンクリート躯体の露出状態の有無",
        evalType: "standard",
        groupId: "group_kiso",
        finishMaterialKey: "モルタル仕上げ・その他塗り仕上げ",
      },
      {
        id: "item35",
        num: 35,
        name: "その他仕上げ",
        desc: "上記コンクリート直仕上げ、又は、モルタル仕上げその他塗り仕上げにおける幅0.3mm以上のひび割れの有無",
        evalType: "standard",
        groupId: "group_kiso",
        finishMaterialKey: "その他仕上げ",
      },
      {
        id: "item36",
        num: 36,
        name: "鉄筋露出",
        desc: "鉄筋の露出の有無",
        evalType: "standard",
        groupId: "group_kiso",
      },
      {
        id: "item37",
        num: 37,
        name: "基礎沈下",
        desc: "基礎の沈下等の有無",
        evalType: "standard",
        groupId: "group_kiso",
      },
      {
        id: "item38",
        num: 38,
        name: "基礎天端高さ",
        desc: "基礎天端と地盤面（接地面）からの高さ（最も高い箇所）",
        evalType: "select",
        options: [{ label: "高さ", choices: ["30cm＞", "30cm≦", "40cm≦"] }],
        groupId: "group_kiso",
      },
      {
        id: "item39",
        num: 39,
        name: "設備配管隙間",
        desc: "設備配管の基礎貫通部の隙間の有無",
        evalType: "standard",
        groupId: "group_kiso",
      },
      // 外壁グループ (40-57)
      {
        id: "item40",
        num: 40,
        name: "外壁ひび割れ",
        desc: "幅0.5㎜以上のひび割れ、又は広範囲に及ぶひび割れ（塗装仕上げ等部分のひび割れは除く）、穴の有無",
        evalType: "standard",
        sub: "【木造】",
        options: [
          {
            label: "外壁の種類",
            choices: [
              "吹付タイル",
              "モルタル塗り",
              "サイディングボード",
              "その他板状",
              "タイル貼り",
            ],
          },
        ],
        groupId: "group_gaiheki",
        groupLabel: "外壁",
      },
      {
        id: "item41",
        num: 41,
        name: "外壁欠損",
        desc: "深さ20㎜以上の欠損、又は広範囲に及ぶ欠損（塗装仕上げ等部分の欠損は除く）の有無",
        evalType: "standard",
        groupId: "group_gaiheki",
      },
      {
        id: "item42",
        num: 42,
        name: "コンクリート劣化",
        desc: "コンクリートの著しい劣化の有無（ ジャンカ又は幅0.5㎜未満のひび割れ、深さ20㎜未満の欠損が広範囲に発生していない事）",
        evalType: "standard",
        sub: "コンクリート打ち放し",
        groupId: "group_gaiheki",
      },
      {
        id: "item43",
        num: 43,
        name: "さび汁・白華",
        desc: "さび汁、エフロレッセンス(白華現象)、ジャンカの有無",
        evalType: "standard",
        groupId: "group_gaiheki",
      },
      {
        id: "item44",
        num: 44,
        name: "鉄筋露出",
        desc: "鉄筋の露出の有無",
        evalType: "standard",
        options: [
          { label: "柱サイズ", choices: ["105≧", "105＜", "120≦", "不明"] },
        ],
        groupId: "group_gaiheki",
      },
      {
        id: "item45",
        num: 45,
        name: "下地材劣化",
        desc: "下地材まで到達するひび割れ、穴、欠損、浮き、はらみ又は剥落の有無（0.5mm以上のひび割れ）",
        evalType: "standard",
        options: [
          { label: "外壁", choices: ["通気無", "通気工法", "湿式", "乾式"] },
        ],
        groupId: "group_gaiheki",
      },
      {
        id: "item46",
        num: 46,
        name: "タイル劣化",
        desc: "複数のタイル等にまたがったひび割れ又は欠損の有無",
        evalType: "standard",
        sub: "タイル塗装、仕上貼り構造",
        groupId: "group_gaiheki",
      },
      {
        id: "item47",
        num: 47,
        name: "鉄筋露出(RC)",
        desc: "鉄筋の露出の有無",
        evalType: "standard",
        sub: "【鉄筋コンクリート造】",
        options: [
          {
            label: "コンクリート面仕上材",
            choices: [
              "コンクリート打放（増打無）",
              "吹付タイル",
              "モルタル塗り（15mm以上）",
              "タイル貼り",
              "石貼り",
            ],
          },
        ],
        groupId: "group_gaiheki",
      },
      {
        id: "item48",
        num: 48,
        name: "仕上材せり上がり",
        desc: "仕上材のせり上がり、膨らみ、浮き、広範囲に及ぶ剥がれの有無※",
        evalType: "standard",
        sub: "※地上及び廊下階段から傍観できる範囲、及び打診棒により地上から2m内外の届く範囲\n　（建物の使用状況により実施しない場合有）",
        groupId: "group_gaiheki",
      },
      {
        id: "item49",
        num: 49,
        name: "板状仕上材割れ",
        desc: "板状の仕上材の全板幅に渡る割れの有無",
        evalType: "standard",
        sub: "サイディングその他板状",
        groupId: "group_gaiheki",
      },
      {
        id: "item50",
        num: 50,
        name: "板状仕上材かけ",
        desc: "板状の仕上材の一部のかけ損じ、穴、せり上がり、膨らみや、下地材が露出している状態の有無",
        evalType: "standard",
        groupId: "group_gaiheki",
      },
      {
        id: "item51",
        num: 51,
        name: "金属板状仕上材錆",
        desc: "金属である板状の仕上材に著しい錆が認められ、欠損又は穴あきに至るおそれのある状態の有無",
        evalType: "standard",
        sub: "【鉄骨】",
        options: [
          {
            label: "外壁の種類",
            choices: [
              "PCパネル",
              "ALC板吹付仕上",
              "カーテンウォール",
              "その他湿式工法（モルタル等）",
              "乾式工法（サイディング等）",
              "ALC板タイル貼仕上",
            ],
          },
        ],
        groupId: "group_gaiheki",
      },
      {
        id: "item52",
        num: 52,
        name: "仕上材ひび割れ、欠損",
        desc: "仕上材の部分的なひび割れ、欠損",
        evalType: "standard",
        sub: "【鉄骨】",
        options: [
          {
            label: "外壁の種類",
            choices: [
              "PCパネル",
              "ALC板吹付仕上",
              "カーテンウォール",
              "その他湿式工法（モルタル等）",
              "乾式工法（サイディング等）",
              "ALC板タイル貼仕上",
            ],
          },
        ],
        groupId: "group_gaiheki",
      },
      {
        id: "item53",
        num: 53,
        name: "シーリング",
        desc: "シーリング材の破断、欠損又は著しいひび割れ、硬化の有無（開口部又は外部付属品との取合部も含む）",
        evalType: "standard",
        groupId: "group_gaiheki",
      },
      {
        id: "item54",
        num: 54,
        name: "建具周囲隙間",
        desc: "建具の周囲の隙間の有無",
        evalType: "standard",
        options: [
          {
            label: "庇の出（目測）",
            choices: ["300＞", "300≦", "450≦", "900≦"],
          },
        ],
        groupId: "group_gaiheki",
      },
      {
        id: "item55",
        num: 55,
        name: "軒裏水染み",
        desc: "軒裏の水染み・破損の有無",
        evalType: "standard",
        groupId: "group_gaiheki",
      },
      {
        id: "item56",
        num: 56,
        name: "雨樋破損",
        desc: "雨樋の破損やカビ等の有無",
        evalType: "standard",
        options: [
          {
            label: "軒の出（目測）",
            choices: ["300＞", "300≦", "450≦", "900≦"],
          },
        ],
        groupId: "group_gaiheki",
      },
      {
        id: "item57",
        num: 57,
        name: "設備配管外壁貫通部",
        desc: "設備配管(ガス・給水・給湯・給排気)、エアコン冷媒管等の外壁貫通部の隙間の有無",
        evalType: "standard",
        groupId: "group_gaiheki",
      },
      // 共用部の廊下・階段・エントランスホールグループ (58-71)
      {
        id: "item58",
        num: 58,
        name: "構造-支持部材",
        desc: "支持部材(手摺、支柱、梁等)の著しいぐらつき、ひび割れ又は劣化（さび汁等又は鉄筋の露出を含む）の有無",
        evalType: "standard",
        sub: "共用部の廊下・階段・バルコニー・エントランスホール【構造】",
        groupId: "group_kyoyobu",
        groupLabel: "共用部の廊下・階段・エントランスホール",
      },
      {
        id: "item59",
        num: 59,
        name: "仕上-天井-ひび割れ・欠損等",
        desc: "仕上のひび割れ・欠損・水染み・さび汁・エフロレッセンス(白華現象)・ジャンカ等の有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item60",
        num: 60,
        name: "仕上-天井-シーリング",
        desc: "シーリングの劣化、硬化、貫通部等の隙間の有無",
        evalType: "standard",
        sub: "【天井】",
        groupId: "group_kyoyobu",
      },
      {
        id: "item61",
        num: 61,
        name: "仕上-天井-照明器具",
        desc: "照明器具の固定部の劣化、落下の恐れの有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item62",
        num: 62,
        name: "仕上-手摺壁・内壁-手摺、笠木の劣化、コケ等の有無",
        desc: "手摺、笠木の劣化、コケ等の有無、ぐらつき・錆の有無、パッキン外れ",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item63",
        num: 63,
        name: "仕上-手摺壁・内壁-ひび割れ・欠損等",
        desc: "ひび割れ・欠損・穴・さび汁・エフロレッセンス(白華現象)・ジャンカの有無",
        evalType: "standard",
        sub: "【手摺壁】",
        groupId: "group_kyoyobu",
      },
      {
        id: "item64",
        num: 64,
        name: "仕上-手摺壁・内壁-シーリング",
        desc: "シーリングの劣化、破断、硬化、貫通部等の隙間の有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item65",
        num: 65,
        name: "仕上-手摺壁・内壁-鉄筋の露出の有無",
        desc: "鉄筋の露出の有無",
        evalType: "standard",
        sub: "【仕上】",
        groupId: "group_kyoyobu",
      },
      {
        id: "item66",
        num: 66,
        name: "仕上-床-ひび割れ・欠損等",
        desc: "仕上のひび割れ・欠損・さび汁・エフロレッセンス(白華現象)・ジャンカ等の有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item67",
        num: 67,
        name: "仕上-床-防水層",
        desc: "防水層（排水口廻り、サッシ下端等）の著しいひび割れ、劣化、欠損又は水切り金物の劣化等の有無",
        evalType: "standard",
        sub: "【床】",
        groupId: "group_kyoyobu",
      },
      {
        id: "item68",
        num: 68,
        name: "仕上-床-排水勾配",
        desc: "屋外廊下の排水溝への勾配、水溜まりの懸念の有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item69",
        num: 69,
        name: "仕上-床-排水溝",
        desc: "排水溝、目皿の堆積物、劣化、よごれの有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item70",
        num: 70,
        name: "仕上-床-鉄筋の露出の有無",
        desc: "鉄筋の露出の有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      {
        id: "item71",
        num: 71,
        name: "仕上-床-シーリング",
        desc: "シーリングの劣化、破断、硬化、貫通部等の隙間の有無",
        evalType: "standard",
        groupId: "group_kyoyobu",
      },
      // 屋外階段グループ (72-74)
      {
        id: "item72",
        num: 72,
        name: "屋外階段-仕上-支柱、床、手摺",
        desc: "支柱、床、手摺の著しいぐらつき、傾き、腐朽、錆の有無　又、塗装の剥離の有無",
        evalType: "standard",
        sub: "屋外階段(木造・鉄骨)",
        options: [{ label: "設置", choices: ["該当有", "該当無"] }],
        groupId: "group_okugai_kaidan",
        groupLabel: "屋外階段",
      },
      {
        id: "item73",
        num: 73,
        name: "屋外階段-仕上-階段の段板及び裏側",
        desc: "階段の段板及び裏側の被覆・塗装の剥離、錆、ひび割れの有無",
        evalType: "standard",
        groupId: "group_okugai_kaidan",
      },
      {
        id: "item74",
        num: 74,
        name: "屋外階段-仕上-(木造の場合)接合部金物",
        desc: "木造の場合：接合部金物の腐食の有無",
        evalType: "standard",
        groupId: "group_okugai_kaidan",
      },
    ],
  },
  {
    id: "cat4",
    name: "外部④ 屋根及び屋上",
    shortName: "屋根・屋上",
    color: "from-orange-500 to-orange-600",
    emoji: "🏗️",
    items: [
      // 屋根グループ (75-80)
      {
        id: "item75",
        num: 75,
        name: "屋根ふき材-欠損・ひび割れ",
        desc: "屋根ふき材の欠損、ひび割れ及び損傷の有無",
        evalType: "standard",
        sub: "【屋根】",
        options: [
          {
            label: "屋根仕様",
            choices: [
              "陸屋根",
              "金属板葺き",
              "トタン",
              "スレート瓦屋根",
              "桟瓦葺き",
              "その他",
            ],
          },
        ],
        groupId: "group_yane",
        groupLabel: "屋根",
      },
      {
        id: "item76",
        num: 76,
        name: "屋根ふき材-錆・腐食等",
        desc: "屋根ふき材の錆、腐食等の劣化、コケの繁茂の有無",
        evalType: "standard",
        groupId: "group_yane",
      },
      {
        id: "item77",
        num: 77,
        name: "緊結金物",
        desc: "緊結金物、雪止め金物の割れ、腐食等の劣化、コケの繁茂の有無",
        evalType: "standard",
        groupId: "group_yane",
      },
      {
        id: "item78",
        num: 78,
        name: "軒樋",
        desc: "軒樋の破損、著しいコケの有無",
        evalType: "standard",
        options: [
          { label: "撮影棒による画像確認", choices: ["実施可", "実施不可"] },
        ],
        groupId: "group_yane",
      },
      {
        id: "item79",
        num: 79,
        name: "アンテナ等",
        desc: "アンテナ等の機器の傾き、破損の有無",
        evalType: "standard",
        groupId: "group_yane",
      },
      {
        id: "item80",
        num: 80,
        name: "破風",
        desc: "破風の水染み、捲れ、破損等の劣化",
        evalType: "standard",
        groupId: "group_yane",
      },
      // 屋上グループ (81-91)
      {
        id: "item81",
        num: 81,
        name: "屋上面劣化",
        desc: "屋上面の劣化及び損傷の有無",
        evalType: "standard",
        sub: "【屋上】",
        options: [
          {
            label: "防水工法",
            choices: [
              "アスファルト防水",
              "シート防水",
              "塗膜防水",
              "FRP防水",
              "その他",
            ],
          },
        ],
        groupId: "group_okujou",
        groupLabel: "屋上",
      },
      {
        id: "item82",
        num: 82,
        name: "ひび割れ・反り",
        desc: "歩行上危険なひび割れ、若しくは反りの有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
      {
        id: "item83",
        num: 83,
        name: "伸縮目地材",
        desc: "伸縮目地材のひび割れ、欠損等の劣化、植物の繁茂の有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
      {
        id: "item84",
        num: 84,
        name: "防水層劣化",
        desc: "防水層、保護層のひび割れ、浮き、欠損、劣化の有無",
        evalType: "standard",
        sub: "階段から屋上に登れる場合は目視、不可の場合は撮影棒による画像確認",
        groupId: "group_okujou",
      },
      {
        id: "item85",
        num: 85,
        name: "パラペットのひび割れ・欠損等",
        desc: "パラペットの立ち上がり面のひび割れ、欠損、劣化及び損傷の有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
      {
        id: "item86",
        num: 86,
        name: "笠木のひび割れ・欠損等",
        desc: "笠木のひび割れ、欠損等の劣化、損傷の有無",
        evalType: "standard",
        options: [
          {
            label: "確認方法",
            choices: ["屋上にて目視確認", "撮影棒による画像確認", "実施不可"],
          },
        ],
        groupId: "group_okujou",
      },
      {
        id: "item87",
        num: 87,
        name: "手摺ぐらつき",
        desc: "手摺のぐらつき、錆の発生の有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
      {
        id: "item88",
        num: 88,
        name: "笠木結合部",
        desc: "笠木結合部の緩み、変形の有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
      {
        id: "item89",
        num: 89,
        name: "排水溝ドレーン",
        desc: "排水溝（ドレーンを含む）の詰まり、コケの繁茂、ひび割れ、浮きの有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
      {
        id: "item90",
        num: 90,
        name: "水たまり",
        desc: "水たまりの有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
      {
        id: "item91",
        num: 91,
        name: "架台支持部",
        desc: "架台・支持部分のひび割れ、破損の有無",
        evalType: "standard",
        groupId: "group_okujou",
      },
    ],
  },
  {
    id: "cat5",
    name: "外部⑤ 共用部（管理状況）※C判定は使用、安全上の危険が想定される場合に選択",
    shortName: "管理状況",
    color: "from-cyan-500 to-cyan-600",
    emoji: "🧹",
    items: [
      {
        id: "item92",
        num: 92,
        name: "内装・郵便受け",
        desc: "郵便受けの美観　ラベルシールの剥がれ・へこみ(施錠の調査は対象外)はないか\n内部の清掃状況(開閉できる場合のみ)は良好か",
        evalType: "management",
        sub: "日常の清掃や、点検実施の有無",
      },
      {
        id: "item93",
        num: 93,
        name: "共用廊下・ごみ置場",
        desc: "共有部や、ごみ置き場(屋外のみ)の清掃・管理の状態は良好か",
        evalType: "management",
      },
      {
        id: "item94",
        num: 94,
        name: "駐輪場・駐車場",
        desc: "駐輪場・駐車場(平置きのみ)・スロープの清掃・管理の状態は良好か",
        evalType: "management",
      },
    ],
  },
  {
    id: "cat6",
    name: "鉄筋の有無（検査済証の交付を受けていない場合のみ実施）",
    shortName: "鉄筋",
    color: "from-slate-500 to-slate-600",
    emoji: "🔨",
    items: [
      {
        id: "item95",
        num: 95,
        name: "基礎立ち上がり又は耐力壁等（いずれか一か所）",
        desc: "鉄筋の有無と配筋のピッチの確認（建物状況調査方法に準拠）",
        evalType: "rebar",
        sub: "※鉄筋の有無については、コンクリート内の鉄筋の存在を調査判定欄に「有、無」と表記",
      },
    ],
  },
  {
    id: "cat7",
    name: "シュミットハンマー（非破壊圧縮強度）調査の実施（旧耐震の場合のみ実施）",
    shortName: "シュミット",
    color: "from-stone-500 to-stone-600",
    emoji: "🔧",
    items: [
      {
        id: "item96",
        num: 96,
        name: "基礎立ち上がり、外壁及び内壁等（原則最下階）",
        desc: "強度低下について確認（建物状況調査方法に準拠）",
        evalType: "schmidt",
        sub: "シュミットハンマー（非破壊圧縮強度）調査の実施（旧耐震の場合のみ実施）",
      },
    ],
  },
  {
    id: "cat8",
    name: "その他 遵法性関係",
    shortName: "遵法性",
    color: "from-red-500 to-red-600",
    emoji: "⚠️",
    items: [
      {
        id: "item97",
        num: 97,
        name: "増築等による構造荷重計算不適合",
        desc: "増築等による構造荷重計算不適合の懸念の有無（上階に増築している場合等）",
        evalType: "legal",
      },
      {
        id: "item98",
        num: 98,
        name: "増築、増床部分の地震倒壊懸念",
        desc: "増築、増床部分に地震による倒壊等の懸念の有無（別棟接続等）",
        evalType: "legal",
      },
      {
        id: "item99",
        num: 99,
        name: "用途不整合",
        desc: "検査済証、謄本と実際の使用用途との大きな不整合の有無",
        evalType: "legal",
      },
      {
        id: "item100",
        num: 100,
        name: "検査済証、図面、謄本との不整合",
        desc: "検査済証、図面、謄本と階数や、高さ、形状の不整合の有無",
        evalType: "legal",
      },
      {
        id: "item101",
        num: 101,
        name: "法不適合等の有無-実測値不整合",
        desc: "建物形状の実測値との不整合（建物外周の一片の長さを実測した、平面図との比較）【90％以下は調査判定有】",
        evalType: "freetext",
      },
    ],
  },
];

// ヘルパー関数
export const getCategoryById = (catId: string) =>
  inspectionMaster.find((c) => c.id === catId);
export const getItemById = (itemId: string) => {
  for (const cat of inspectionMaster) {
    const item = cat.items.find((i) => i.id === itemId);
    if (item) return { item, category: cat };
  }
  return null;
};
export const getTotalItemCount = () =>
  inspectionMaster.reduce((sum, cat) => sum + cat.items.length, 0);
